encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random/", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from markdown2 import Markdown
import random as rand

from . import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    entry = util.get_entry(title)
    if entry is None:
        return render(request, "encyclopedia/error.html", {
            "error_msg": f"Entry with title '{title}' does not exist."
        })
    html = Markdown().convert(entry)
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": html
    })

def search(request):
    query = request.GET.get('q')
    if query is not None:
        entries = util.list_entries()
        results = []
        for entry in entries:
            if query.lower() == entry.lower():
                return redirect(reverse("encyclopedia:entry", args=[entry]))
            if query.lower() in entry.lower():
                results.append(entry)
        return render(request, "encyclopedia/search.html", {
            "query": query,
            "entries": results
        })
    return render(request, "encyclopedia/search.html", {
            "query": query,
            "results": results
        })

def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        if util.get_entry(title) is None:
            util.save_entry(title, content)
            return redirect(reverse("encyclopedia:entry", args=[title]))
        else:
            return render(request, "encyclopedia/error.html", {
                "error_msg": f"Entry with title '{title}' already exists."
            })
    return render(request, "encyclopedia/new.html")

def edit(request, title):
    if request.method == 'POST':
        content = request.POST.get('content')
        util.save_entry(title, content)
        return redirect(reverse("encyclopedia:entry", args=[title]))


    entry = util.get_entry(title)
    if entry is None:
        return render(request, "encyclopedia/error.html", {
            "error_msg": f"Entry with title '{title}' does not exist."
        })
    return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": util.get_entry(title)
        })

def random(request):
    entries = util.list_entries()
    title = rand.choice(entries)
    return redirect(reverse("encyclopedia:entry", args=[title]))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit page</h1>
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
            <br>
            <input type="text" class="form-control" name="title" value="{{ title }}" disabled>
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <br>
            <textarea name="content" class="form-control" cols="20" rows="9">{{ content }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ content|safe }}
    <br>
    <br>
    <br>
    <a class="btn btn-primary" href="{% url 'encyclopedia:edit' title %}" role="button">Edit</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }} | Not Found
{% endblock %}

{% block body %}
    <h1>{{ error_msg }}</h1>
    <a href="{% url 'encyclopedia:index' %}">Return home</a>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="'GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create new page</h1>
    <form action="{% url 'encyclopedia:new' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
            <br>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <br>
            <textarea name="content" class="form-control" cols="20" rows="9"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if entries %}
        <h1>Search results for: {{ query }}</h1>
    {% endif %}

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% empty %}
            <h4>No results found, create a <a href="{% url 'encyclopedia:new' %}">page</a> for this entry or return <a href="{% url 'encyclopedia:index' %}">home</a></h5>
        {% endfor %}
    </ul>

{% endblock %}